### ISSUE TITLE
Error: CannotSyncStreams in the third node.

### ISSUE THREAD

**Issue by taito** [iggy-rs/iggy-cluster-sandbox#3]
Ever since commit [eededb54793e6f0528503229fdae5a2d0a2f51d0](https://github.com/iggy-rs/iggy-cluster-sandbox/commit/eededb54793e6f0528503229fdae5a2d0a2f51d0), the third node stops with error message: `Error: CannotSyncStreams` when following the README instruction.

This could be avoided by reverting the line 103 of `node/src/clusters/cluser.rs`.

**Comment by taito** [comment]
Thanks a lot for the quick response!
Do you have any idea at which point the cluster feature would be in the main Iggy?

**Comment by spetz** [comment]
Hopefully in the upcoming months, as at the same time, we'll be trying to make use of the new runtime with `io_uring` and most likely `thread-per-core` architecture in place, so all these things together will take some time to implement :smiley:
